- name: Install Docker dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - gnupg-agent
    - software-properties-common
    - gnupg2
    - bridge-utils
    update_cache: yes
