- name: Install Docker dependencies on Debian based systems
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - gnupg-agent
    - software-properties-common
    - gnupg2
    - bridge-utils
    update_cache: yes
  when:
    - ansible_os_family == "Debian"

# Install brew dependencies on MacOS 
- name: Install Docker dependencies on MacOS
  homebrew:
    name: "{{ packages }}"
  vars:
    packages:
    - 'go'
    - 'go-md2man'
  when:
    - ansible_os_family == "Darwin"