---
- name: Install Docker dependencies
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - gnupg2
      - bridge-utils
    update_cache: yes
    
- name: Install Python packages.
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - docker-py
    state: present
