---
- set_fact:
    ansible_distribution: Ubuntu
    cacheable: yes
    when: 
    - ansible_distribution == "Linux Mint"

- set_fact:
    ansible_distribution_release: "bionic"
    cacheable: yes
    when: 
    - ansible_distribution_release == "tessa" OR 
      ansible_distribution_release == "tricia" OR
      ansible_distribution_release == "tina" OR
      ansible_distribution_release == "tara" OR
      ansible_distribution_release == "hera" OR
      ansible_distribution_release == "juno"

- set_fact:
    ansible_distribution_release: "focal"
    cacheable: yes
    when: 
    - ansible_distribution_release == "ulyana" OR 
      ansible_distribution_release == "ulyssa" OR
      ansible_distribution_release == "uma" OR
      ansible_distribution_release == "una" OR
      ansible_distribution_release == "odin"

- name: Import the Docker repository GPG key
  apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present
      id: 0EBFCD88
  delay: 10
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Add docker apt repo (amd64)
  apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
      state: present
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
    - ansible_architecture == "x86_64" 

- name: Add docker apt repo (arm64)
  apt_repository:
      repo: 'deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
      state: present
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
    - ansible_architecture == "aarch64"
