---
- set_fact:
    ansible_distribution: Ubuntu
    when: 
    - ansible_distribution == "Linux Mint"

- set_fact:
    ansible_distribution_release: "bionic"
    when: (ansible_facts['ansible_distribution_release'] == "tessa") or
          (ansible_facts['ansible_distribution_release'] == "tricia") or
          (ansible_facts['ansible_distribution_release'] == "tina") or
          (ansible_facts['ansible_distribution_release'] == "tara") or
          (ansible_facts['ansible_distribution_release'] == "hera") or
          (ansible_facts['ansible_distribution_release'] == "juno")

- set_fact:
    ansible_distribution_release: "focal"
    when: (ansible_facts['ansible_distribution_release'] == "ulyana") or
          (ansible_facts['ansible_distribution_release'] == "ulyssa") or
          (ansible_facts['ansible_distribution_release'] == "uma") or
          (ansible_facts['ansible_distribution_release'] == "una") or
          (ansible_facts['ansible_distribution_release'] == "odin")

- set_fact:
    ansible_distribution_release: "jammy"
    when: (ansible_facts['ansible_distribution_release'] == "vanessa") or
          (ansible_facts['ansible_distribution_release'] == "vera") or
          (ansible_facts['ansible_distribution_release'] == "victoria") or 
          (ansible_facts['ansible_distribution_release'] == "virginia")

- name: Configure Docker repository
  block:
    - name: Get repository GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker.asc
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

    - name: Import the Docker repository GPG key
      apt_key:
          url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
          keyring: /usr/share/keyrings/docker.asc
          state: present
          id: 0EBFCD88
      delay: 10
      when: 
        - ansible_distribution == "Ubuntu"

    - name: Add docker apt repo (amd64)
      apt_repository:
          repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
          state: present
          update_cache: no
      when: 
        - ansible_distribution == "Ubuntu"
        - ansible_architecture == "x86_64" 

    - name: Add docker apt repo (arm64)
      apt_repository:
          repo: 'deb [arch=arm64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
          state: present
          update_cache: no
      when: 
        - ansible_distribution == "Ubuntu"
        - ansible_architecture == "aarch64"

    - name: Add docker apt repo (armhf)
      apt_repository:
          repo: 'deb [arch=armhf signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} bionic stable'
          state: present
          update_cache: no
      when: 
        - ansible_distribution == "Ubuntu"
        - ansible_architecture == "armv7l"

- name: apt-get update
  shell: apt-get update
  ignore_errors: true