---
- set_fact:
    ansible_distribution: Ubuntu
    when: 
    - ansible_distribution == "Linux Mint"

- set_fact:
    ansible_distribution_release: "bionic"
    when: (ansible_facts['ansible_distribution_release'] == "tessa") or
          (ansible_facts['ansible_distribution_release'] == "tricia") or
          (ansible_facts['ansible_distribution_release'] == "tina") or
          (ansible_facts['ansible_distribution_release'] == "tara") or
          (ansible_facts['ansible_distribution_release'] == "hera") or
          (ansible_facts['ansible_distribution_release'] == "juno")

- set_fact:
    ansible_distribution_release: "focal"
    when: (ansible_facts['ansible_distribution_release'] == "ulyana") or
          (ansible_facts['ansible_distribution_release'] == "ulyssa") or
          (ansible_facts['ansible_distribution_release'] == "uma") or
          (ansible_facts['ansible_distribution_release'] == "una") or
          (ansible_facts['ansible_distribution_release'] == "odin")

- set_fact:
    ansible_distribution_release: "jammy"
    when: (ansible_facts['ansible_distribution_release'] == "vanessa") or
          (ansible_facts['ansible_distribution_release'] == "vera") or
          (ansible_facts['ansible_distribution_release'] == "victoria") or 
          (ansible_facts['ansible_distribution_release'] == "virginia")

- name: Import the Docker repository GPG key
  apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present
      id: 0EBFCD88
  delay: 10
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Add docker apt repo (amd64)
  apt_repository:
      repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
      state: present
      update_cache: no
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
    - ansible_architecture == "x86_64" 

- name: Add docker apt repo (arm64)
  apt_repository:
      repo: 'deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
      state: present
      update_cache: no
  when: 
    - ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
    - ansible_architecture == "aarch64"

- name: apt-get update
  shell: apt-get update
  ignore_errors: true