- name: Remove Docker old version
  ansible.builtin.shell: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove -y $pkg; done

- name: Install python libraries
  pip:
    name:
    - PyYAML
    - docker
    # - docker-compose
    # - docker-py
    - requests
    executable: pip3
    state: present

- name: Install Docker package
  package:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: latest
  register: docker_installed
  tags: docker
  delay: 10

# - name: Add Docker Plugin. Loki-docker-driver
#   shell: "docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
#   register: install_plugin_docker_loki
#   ignore_errors: yes
