---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when:
    - ansible_architecture == "x86_64"
    - docker_compose_current_version.stdout is defined
    - docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
  when:
    - ansible_architecture == "x86_64"

- name: Install Docker Compose (ARM64)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - docker-compose
    state: present
  when:
    - ansible_architecture == "aarch64"