---
# tasks file for docker

# - include_tasks: 00-ensure-authorized-keys.yml
#   tags: docker-ensure-authorized-keys

- include_tasks: 01-dependencies.yml
  tags: docker-dependencies

- include_tasks: 02-repo.yml
  tags: docker-repo

- include_tasks: 03-install.yml
  tags: docker-install

# - include_tasks: 04-install_compose.yml
#   tags: docker-compose-install

- include_tasks: 05-users.yml
  tags: docker-users

# - include_tasks: 05-create_group.yml
#   tags: docker_create_group-dependencies
